import { KeySignature, LevelAccidentType, NoteName, ScaleType } from "./enums";
import { WHITE_NOTES_ALL_OCTAVES, NOTES_SHARP_ALL_OCTAVES, NOTES_FLAT_ALL_OCTAVES } from "./notes";
import { Note } from "./types";

export const FLAT_KEY_SIGNATURES = [
  KeySignature.F,
  KeySignature.Bb,
  KeySignature.Eb,
  KeySignature.Ab,
  KeySignature.Db,
  KeySignature.Gb,
  KeySignature.Cb,
  KeySignature.Dm,
  KeySignature.Gm,
  KeySignature.Cm,
  KeySignature.Fm,
  KeySignature.Bbm,
  KeySignature.Ebm,
  KeySignature.Abm,
];
export const SHARP_KEY_SIGNATURES = [
  KeySignature.C,
  KeySignature.G,
  KeySignature.D,
  KeySignature.A,
  KeySignature.E,
  KeySignature.B,
  KeySignature["F#"],
  KeySignature["C#"],
  KeySignature.Am,
  KeySignature.Em,
  KeySignature.Bm,
  KeySignature["F#m"],
  KeySignature["C#m"],
  KeySignature["G#m"],
  KeySignature["D#m"],
  KeySignature["A#m"],
];

export const MAJOR_KEY_SIGNATURES = [
  KeySignature.Cb,
  KeySignature.Gb,
  KeySignature.Db,
  KeySignature.Ab,
  KeySignature.Eb,
  KeySignature.Bb,
  KeySignature.F,
  KeySignature.C,
  KeySignature.G,
  KeySignature.D,
  KeySignature.A,
  KeySignature.E,
  KeySignature.B,
  KeySignature["F#"],
  KeySignature["C#"],
];
export const MINOR_KEY_SIGNATURES = [
  KeySignature.Abm,
  KeySignature.Ebm,
  KeySignature.Bbm,
  KeySignature.Fm,
  KeySignature.Cm,
  KeySignature.Gm,
  KeySignature.Dm,
  KeySignature.Am,
  KeySignature.Em,
  KeySignature.Bm,
  KeySignature["F#m"],
  KeySignature["C#m"],
  KeySignature["G#m"],
  KeySignature["D#m"],
  KeySignature["A#m"],
];

export const MAJOR_KEY_SIGNATURES_SHARP = [
  KeySignature.C,
  KeySignature.G,
  KeySignature.D,
  KeySignature.A,
  KeySignature.E,
  KeySignature.B,
  KeySignature["F#"],
  KeySignature["C#"],
];
export const MAJOR_KEY_SIGNATURES_FLAT = [
  KeySignature.F,
  KeySignature.Bb,
  KeySignature.Eb,
  KeySignature.Ab,
  KeySignature.Db,
  KeySignature.Gb,
  KeySignature.Cb,
];
export const MINOR_KEY_SIGNATURES_SHARP = [
  KeySignature.Am,
  KeySignature.Em,
  KeySignature.Bm,
  KeySignature["F#m"],
  KeySignature["C#m"],
  KeySignature["G#m"],
  KeySignature["D#m"],
  KeySignature["A#m"],
];
export const MINOR_KEY_SIGNATURES_FLAT = [
  KeySignature.Dm,
  KeySignature.Gm,
  KeySignature.Cm,
  KeySignature.Fm,
  KeySignature.Bbm,
  KeySignature.Ebm,
  KeySignature.Abm,
];

export const keySignatureNotes = {
  [KeySignature.Cb]: ["cb", "db", "eb", "fb", "gb", "ab", "bb"],
  [KeySignature.Gb]: ["gb", "ab", "bb", "cb", "db", "eb", "f"],
  [KeySignature.Db]: ["db", "eb", "f", "gb", "ab", "bb", "c"],
  [KeySignature.Ab]: ["ab", "bb", "c", "db", "eb", "f", "g"],
  [KeySignature.Eb]: ["eb", "f", "g", "ab", "bb", "c", "d"],
  [KeySignature.Bb]: ["bb", "c", "d", "eb", "f", "g", "a"],
  [KeySignature.F]: ["f", "g", "a", "bb", "c", "d", "e"],
  [KeySignature.C]: ["c", "d", "e", "f", "g", "a", "b"],
  [KeySignature.G]: ["g", "a", "b", "c", "d", "e", "f#"],
  [KeySignature.D]: ["d", "e", "f#", "g", "a", "b", "c#"],
  [KeySignature.A]: ["a", "b", "c#", "d", "e", "f#", "g#"],
  [KeySignature.E]: ["e", "f#", "g#", "a", "b", "c#", "d#"],
  [KeySignature.B]: ["b", "c#", "d#", "e", "f#", "g#", "a#"],
  [KeySignature["F#"]]: ["f#", "g#", "a#", "b", "c#", "d#", "e#"],
  [KeySignature["C#"]]: ["c#", "d#", "e#", "f#", "g#", "a#", "b#"],

  [KeySignature.Abm]: ["ab", "bb", "cb", "db", "eb", "fb", "gb"],
  [KeySignature.Ebm]: ["eb", "f", "gb", "ab", "bb", "cb", "db"],
  [KeySignature.Bbm]: ["bb", "c", "db", "eb", "f", "gb", "ab"],
  [KeySignature.Fm]: ["f", "g", "ab", "bb", "c", "db", "eb"],
  [KeySignature.Cm]: ["c", "d", "eb", "f", "g", "ab", "bb"],
  [KeySignature.Gm]: ["g", "a", "bb", "c", "d", "eb", "f"],
  [KeySignature.Dm]: ["d", "e", "f", "g", "a", "bb", "c"],
  [KeySignature.Am]: ["a", "b", "c", "d", "e", "f", "g"],
  [KeySignature.Em]: ["e", "f#", "g", "a", "b", "c", "d"],
  [KeySignature.Bm]: ["b", "c#", "d", "e", "f#", "g", "a"],
  [KeySignature["F#m"]]: ["f#", "g#", "a", "b", "c#", "d", "e"],
  [KeySignature["C#m"]]: ["c#", "d#", "e", "f#", "g#", "a", "b"],
  [KeySignature["G#m"]]: ["g#", "a#", "b", "c#", "d#", "e", "f#"],
  [KeySignature["D#m"]]: ["d#", "e#", "f#", "g#", "a#", "b", "c#"],
  [KeySignature["A#m"]]: ["a#", "b#", "c#", "d#", "e#", "f#", "g#"],
} as Record<KeySignature, NoteName[]>;

export const chromatickeySignatureNotes = {
  [KeySignature.Cb]: ["cb", "c", "db", "d", "eb", "fb", "f", "gb", "g", "ab", "a", "bb"],
  [KeySignature.Gb]: ["gb", "g", "ab", "a", "bb", "cb", "c", "db", "d", "eb", "e", "f"],
  [KeySignature.Db]: ["db", "d", "eb", "e", "f", "gb", "g", "ab", "a", "bb", "b", "c"],
  [KeySignature.Ab]: ["ab", "a", "bb", "b", "c", "db", "d", "eb", "e", "f", "gb", "g"],
  [KeySignature.Eb]: ["eb", "e", "f", "gb", "g", "ab", "a", "bb", "b", "c", "db", "d"],
  [KeySignature.Bb]: ["bb", "b", "c", "db", "d", "eb", "e", "f", "gb", "g", "ab", "a"],
  [KeySignature.F]: ["f", "gb", "g", "g#", "a", "bb", "b", "c", "db", "d", "eb", "e"],
  [KeySignature.C]: ["c", "db", "d", "d#", "e", "f", "f#", "g", "ab", "a", "bb", "b"],
  [KeySignature.G]: ["g", "ab", "a", "bb", "b", "c", "c#", "d", "eb", "e", "f", "f#"],
  [KeySignature.D]: ["d", "eb", "e", "f", "f#", "g", "g#", "a", "bb", "b", "c", "c#"],
  [KeySignature.A]: ["a", "bb", "b", "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#"],
  [KeySignature.E]: ["e", "f", "f#", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#"],
  [KeySignature.B]: ["b", "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#"],
  [KeySignature["F#"]]: ["f#", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#", "e", "f"],
  [KeySignature["C#"]]: ["c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b", "c"],

  [KeySignature.Abm]: ["ab", "a", "bb", "cb", "c", "db", "d", "eb", "fb", "f", "gb", "g"],
  [KeySignature.Ebm]: ["eb", "e", "f", "gb", "g", "ab", "a", "bb", "b", "c", "db", "d"],
  [KeySignature.Bbm]: ["bb", "b", "c", "db", "d", "eb", "e", "f", "gb", "g", "ab", "a"],
  [KeySignature.Fm]: ["f", "gb", "g", "g#", "a", "bb", "b", "c", "db", "d", "eb", "e"],
  [KeySignature.Cm]: ["c", "db", "d", "d#", "e", "f", "f#", "g", "ab", "a", "bb", "b"],
  [KeySignature.Gm]: ["g", "ab", "a", "bb", "b", "c", "c#", "d", "eb", "e", "f", "f#"],
  [KeySignature.Dm]: ["d", "eb", "e", "f", "f#", "g", "g#", "a", "bb", "b", "c", "c#"],
  [KeySignature.Am]: ["a", "bb", "b", "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#"],
  [KeySignature.Em]: ["e", "f", "f#", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#"],
  [KeySignature.Bm]: ["b", "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#"],
  [KeySignature["F#m"]]: ["f#", "g", "g#", "a", "a#", "b", "c", "c#", "d", "d#", "e", "f"],
  [KeySignature["C#m"]]: ["c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b", "c"],
  [KeySignature["G#m"]]: ["g#", "a", "a#", "b", "c", "c#", "d", "d#", "e", "f", "f#", "g"],
  [KeySignature["D#m"]]: ["d#", "e", "f", "f#", "g", "g#", "a", "a#", "b", "c", "c#", "d"],
  [KeySignature["A#m"]]: ["a#", "b", "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a"],
} as Record<KeySignature, NoteName[]>;

export const accidentNoteSequences: Record<LevelAccidentType, Note[]> = {
  [LevelAccidentType.None]: WHITE_NOTES_ALL_OCTAVES,
  [LevelAccidentType["#"]]: NOTES_SHARP_ALL_OCTAVES,
  [LevelAccidentType.b]: NOTES_FLAT_ALL_OCTAVES,
  // [Accident["#b"]]: NOTES_SHARP_FLAT_ALL_OCTAVES,
  // [Accident.x]: DOUBLE_SHARP_NOTES_ALL_OCTAVES,
  // [Accident.bb]: DOUBLE_FLAT_NOTES_ALL_OCTAVES,
  // [Accident.All]: POSSIBLE_NOTES_ALL_OCTAVES,
};

export const scaleTypeNoteSequences = {
  [ScaleType.Chromatic]: chromatickeySignatureNotes,
  [ScaleType.Diatonic]: keySignatureNotes,
} as Record<ScaleType, Record<KeySignature, NoteName[]>>;
